name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Linux dependencies for Cypress
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev \
            libgtk-3-0 \
            libnss3 \
            libasound2 \
            libxss1 \
            libxtst6 \
            xauth \
            xvfb

      - name: Build project
        run: npm run build

      - name: Start server
        run: npm start &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run