name: Libreria

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgbm-dev \
            libgtk-3-0 \
            libnss3 \
            libasound2 \
            libxss1 \
            libxtst6 \
            xauth \
            xvfb

      - name: Install npm dependencies
        run: npm ci

      - name: Run Cypress
        run: npx cypress run